### ISSUE TITLE
Binary release of Mac version of NanoShaper is dynamically linked...

### ISSUE THREAD

**Issue by intendo** [lwwilson1/mesh_routines#2]
@lwwilson1 when you created the Executables for the releases, the Mac version is dynamically linked.

```
(bash) $ !$ ~/Downloads/NanoShaper_OSX
dyld: Library not loaded: libCGAL.11.dylib
  Referenced from: ~/Downloads/NanoShaper_OSX
  Reason: image not found
Abort trap: 6
(bash) $ otool -L ~/Downloads/NanoShaper_OSX
~/Downloads/NanoShaper_OSX:
	/usr/local/opt/mpfr/lib/libmpfr.4.dylib (compatibility version 6.0.0, current version 6.4.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.0.0)
	libCGAL.11.dylib (compatibility version 11.0.0, current version 11.0.1)
	/usr/local/opt/boost/lib/libboost_thread-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_chrono-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_date_time-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_atomic-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

Without GCC and Boost installed, there would be even be more missing dependencies.

Can you release a statically linked version of NanoShaper and msms for MacOS?

**Comment by lwwilson1** [comment]
Ahh, thank you for catching this. I'll get on it now.

**Comment by lwwilson1** [comment]
If you have access to a Mac, would you mind testing this by running ./NanoShaper in this directory? I don't have access to another Mac other than mine at the moment, but it looks like I've removed all dependencies other than the system ones, so *I think* it should be capable of working on anything past Mountain Lion. 

[NS test.zip](https://github.com/lwwilson1/mesh_routines/files/5088156/NS.test.zip)

**Comment by intendo** [comment]
otool -L NanoShaper, produced:
NanoShaper:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

I was able to run the executable just fine. I will put it back into the APBS testing for the Mac.

Thank you so much!

@sobolevnrm and I really appreciate you help. I think this issue can be closed. If I run into problems, I might ask to reopen it.

**Comment by intendo** [comment]
Sorry, could you make a release of the NanoShaper_OSX binary so that I can retrieve it during the build/test process we use in Github Actions?

**Comment by lwwilson1** [comment]
I've made a new release now--the release tag v1.6 has the new statically linked NanoShaper_OSX binary in it
