### ISSUE TITLE
Remove support for msms?

### ISSUE THREAD

**Issue by lwwilson1** [lwwilson1/mesh_routines#3]
@intendo Since I've only been using NanoShaper for quite a while now and haven't touched msms in a long time, but the msms executable won't actually work on any Mac running Catalina (or future versions). There's no source code available, only binaries, and the most recent one is compiled only for PowerPC and i386 architectures, so no 64-bit support. The quality of the msms surfaces is worse in every way anyway, so this isn't a huge loss, and I'll likely end up fully removing msms and support for it in TABI-PB (and from this repository). 

I think PB-SAM might have some sort of msms dependency, but it's something that could be updated to NanoShaper. It's been so long since I dug into the PB-SAM details I'll have to take a look and see where/ if there's a dependency there.

**Comment by intendo** [comment]
I have passed on the information to @sobolevnrm so that he can help make a decision on how to proceed.

Thanks.

**Comment by intendo** [comment]
We have removed all the references to msms in APBS code and documentation.

Thanks

**Comment by sobolevnrm** [comment]
Is this resolved?  Can we close it?
